### ISSUE TITLE
Keybinding support

### ISSUE THREAD

**Issue by Ei30metry** [kraanzu/termtyper#10]
Hi, I tried your TUI program and really liked it, but the lack of keybinding supports for deleting single words and lines slows the typing process down a bit. It would be great to have keybinding features in the next update!

**Comment by kraanzu** [comment]
Hey there! 
> I tried your TUI program and really liked it 

Thank you so much <3

> deleting single words 

You can delete words using `ctrl+w`
I guess I should really add a help menu for this. 

> and lines

By `line` did you mean up to a full-stop? 
If yes, then its possible and i'll add it right away :smile: 
But deleting till the first letter of line is not possible since the rendering of the paragraph really depends upon the size of the terminal :disappointed:

**Comment by kraanzu** [comment]
I've added `ctrl+l` keybinding for a sentence delete, the delimited being a full stop :)

**Comment by jclsn** [comment]
Is there a keybinding for starting the next test? I always have to use the mouse, which is annoying

**Comment by kraanzu** [comment]
Hi @jclsn !

Yes currently if you press `escape`, it'll go back to the typing screen and will start a new test :)

**Comment by jclsn** [comment]
Thanks, found that out by now as well. I think pressing return would be more intuitive though!
